### ISSUE TITLE
Criar endpoint de exclusão de categoria

### ISSUE THREAD

**Issue by tcortega** [lab-software-uvv/stock-solution-app#15]
- [x] Criar a rota `DELETE /categories/{id}` para a exclusão de categorias:
    - Antes de excluir, verificar se existem produtos associados à categoria.
    - Implementar lógica para desassociar os produtos da categoria a ser excluída.
    - Excluir a categoria do banco de dados.
    - Retornar status `404 Not Found` caso a categoria não exista.
    - Retornar status `200 OK` com uma mensagem de confirmação em caso de exclusão bem-sucedida.
    - Registrar a ação de exclusão para fins de auditoria.
    - Em caso de erro, como falha na desassociação dos produtos, retornar status de resposta apropriado com mensagem de erro (ex: `500 Internal Server Error`).

**Comment by leandro-santos-abreu** [comment]
@tcortega, como ainda não existe nada criado para a parte de Produtos, tais validações/exclusões em cascata precisarão ser finalizadas futuramente.
