### ISSUE TITLE
Criação do endpoint de login

### ISSUE THREAD

**Issue by tcortega** [lab-software-uvv/stock-solution-app#6]
- [ ] Criar a rota `POST /auth/login` para autenticação de usuários.
    - Endpoint responsável pela verificação das credenciais do usuário.

- [ ] Implementar a lógica no controller de autenticação (`AuthController`) para verificar as credenciais do usuário:
    - Comparar a senha inserida com a senha criptografada armazenada no banco de dados.
    - Verificar se o e-mail existe no banco de dados.

- [ ] Se as credenciais estiverem corretas:
    - Gerar um token JWT (ou semelhante) para a sessão do usuário.
    - Retornar o token para o frontend.

- [ ] Em caso de credenciais inválidas ou qualquer outro erro:
    - Retornar uma mensagem de erro apropriada com status adequado para o frontend.

**Comment by CaioSchneiderSousa** [comment]
@lab-software-uvv/backend
