### ISSUE TITLE
Criação do sistema de Roles

### ISSUE THREAD

**Issue by tcortega** [lab-software-uvv/stock-solution-app#8]
- [ ] Definir um modelo de Role no banco de dados com atributos como nome e descrição.
    - Inserir os três roles estáticos: Administrador, Gerente, Funcionário.

- [ ] Integrar a lógica de convites com a de roles:
    - Quando um código de convite é criado, associar uma role específica a esse código.
    - Durante o registro, quando o código de convite é validado, a role associada ao código deve ser atribuída ao novo usuário.

- [ ] Implementar lógica no sistema de autenticação para reconhecer e aplicar a role de cada usuário:
    - Durante o processo de login, associar a role ao token de autenticação ou sessão do usuário.
    - Em endpoints que requerem controle de acesso, verificar a role do usuário para garantir que ele tenha as permissões necessárias.

- [ ] Implementar mecanismos de segurança para garantir que apenas usuários com as permissões apropriadas (como Administradores) possam criar códigos de convite com roles de "Gerente" e etc...

**Comment by CaioSchneiderSousa** [comment]
@lab-software-uvv/backend
